### ISSUE TITLE
User class raise errors when the user is actually empty

### ISSUE THREAD

**Issue by bzwei** [ManageIQ/manageiq-api-common#41]
Two cases can lead to an empty user.
1. The request header does not contain user info
2. The code does not parse the header correctly.

When the user is empty, any accessor method fails, for example `User.email`
Rails controller converts key `x-rh-identity` to `HTTP_X_RH_IDENTITY`. The parsing code should read from the modified key.

**Comment by Fryguy** [comment]
@bzwei The HTTP_X_RH_IDENTITY thing should be fixed now with #37 .  Do you still have this issue?

**Comment by bzwei** [comment]
Yes. Issue 2 has been solved through #37.
